### PR TITLE
FIX THE PLAZA POST REPLY ISSUE

### PR DESCRIPTION
**Pull request by hunxjunedo**
wohoo! fixed the issue #17  and now the it works as expected. Moreover, reduced the unnecessary number of requests being made to the Hive's API, alongside with rendering this new component in the main component `page` rather than every child `commentItem` to reduce RAM and CPU usage.

Screenshot from 2024-05-28 21-08-01
Screenshot from 2024-05-28 21-08-14
Screenshot from 2024-05-28 21-09-23

### CODE REVIEW

**Comment by sktbrd** [comment]
we had some advance in the ui on this already that I think is looking better, can we keep only the cpu and ram optimation in that. one ? 

dont forget to attach and Base ETH address in the next one , thanks a lot

**Comment by hunxjunedo** [comment]
> we had some advance in the ui on this already that I think is looking better, can we keep only the cpu and ram optimation in that. one ?
> 
> dont forget to attach and Base ETH address in the next one , thanks a lot

but I think the current advancement doesn't show the payout value, existing replies and doesn't allow to reply with media. It was the main requirement if you check in the issue conversation.

**Comment by webgnar** [comment]
can we restyle @hunxjunedo 's code to make the UI look how we had it? @sktbrd .
should i close this issue?

**Comment by sktbrd** [comment]
> I don't see how this is different, and why is it turning out to be a problem. I mean it does show merging conflicts due the the commit by @r4topunk which did the refactor, other than that it's as you guys wanted. If you guys want I can resolve the merge conflicts.

No problem. You being awesome with your contributions and interest. We are very thankful. what we are trying to say is that the app already looks like this: 

image

versus this 

image


So what I tried to ask, was if we could keep the RAM and CPU improvements but not the UI 

or may be if you wanna chat with us in discord we can align better next steps. 

Also, sorry we suck in this GITHUB operation, we are new to all this.

**Comment by hunxjunedo** [comment]
Yeah i think the conversation on discord would be more fruitful. Drop some server link or username

**Comment by sktbrd** [comment]
https://basescan.org/tx/0x8c41309137e6b90d023f3622eaf6a34669e61637851620752b743aa0b3a60085

@hunxjunedo sent you some appreciation for your effort and time spent. 

our discord is https://discord.gg/skateboard

**Comment by r4topunk** [comment]
Hello,

I apologize for the delay in reviewing this commit. Yes, this has been dragging on longer than it should have, and I apologize for that, @hunxjunedo .

I reviewed the code and talked with @sktbrd on Discord. I'd like to point out a few things.

As we are constantly changing the repository in search of improvements, we believe that the code you used may not be the best way to handle these replies.

I would like the changes to be submitted as separate PRs so that we can better understand the impact of each change. Mainly because the structure of this section has been refactored. This also allows us to accept parts of the changes while we correctly decide the progress of the reply PR.

I hope you understand our position regarding these changes. We are very happy with your contributions and want to strengthen this relationship and bring you even closer. However, we need you to understand that we do not feel comfortable merging the PR in its current form.

**Comment by hunxjunedo** [comment]
@r4topunk alright, so where are we heading now ? What do you want me to do ?

**Pull request closed without merging**
