### PR TITLE
modifications to the modal tip and tip carousel

### PR DESCRIPTION
**Pull request by Jhonattan2121**
Screenshot from 2024-11-03 10-26-40

https://github.com/user-attachments/assets/b89c84d6-4da1-47c1-a160-6d259b03978e

### CODE REVIEW

**Comment by Jhonattan2121** [comment]
https://github.com/user-attachments/assets/f88c00c8-67bb-4deb-bacd-b5cc27338136

**Comment by Jhonattan2121** [comment]
https://github.com/SkateHive/nextskateapp/pull/103/commits/a4dbc1586cfd7e7e64c30afd4083d14e214cf3e9

https://github.com/user-attachments/assets/03c6ad17-03a5-447e-805b-97d6f6e50ca1

**Comment by Jhonattan2121** [comment]
https://github.com/SkateHive/nextskateapp/pull/103/commits/12fd0d8a8269f2ef2b5fd0fcbd1f0be98ebbe962
Screenshot From 2024-11-06 20-08-07

**Comment by sktbrd** [comment]
@Jhonattan2121 please , do diferente PRs for different matters 

why the @ to search usernames ?

**Pull request merged**
